# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/spotify-etl',
                'doc_host': 'https://LearnThinkCreate.github.io',
                'git_url': 'https://github.com/LearnThinkCreate/spotify-etl',
                'lib_path': 'spotify_etl'},
  'syms': {'spotify_etl.core': {'spotify_etl.core.foo': ('core.html#foo', 'spotify_etl/core.py')}}}