# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/spotify-etl',
                'doc_host': 'https://LearnThinkCreate.github.io',
                'git_url': 'https://github.com/LearnThinkCreate/spotify-etl',
                'lib_path': 'spotify_etl'},
  'syms': { 'spotify_etl.core': { 'spotify_etl.core.clean_streaming_history': ( 'pull_history.html#clean_streaming_history',
                                                                                'spotify_etl/core.py'),
                                  'spotify_etl.core.extract_streaming_history': ( 'pull_history.html#extract_streaming_history',
                                                                                  'spotify_etl/core.py'),
                                  'spotify_etl.core.get_pickle_data': ('pull_history.html#get_pickle_data', 'spotify_etl/core.py')}}}