# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_Clean_Data.ipynb.

# %% auto 0
__all__ = ['clean_title']

# %% ../01_Clean_Data.ipynb 12
# |code-fold: true
def clean_title(title: str):
    # Remove everything in parentheses
    title = re.sub(r"\(.*\)", "", title)
    # Remove everything in brackets
    title = re.sub(r"\[.*\]", "", title)
    # Remove everything after a dash
    title = re.sub(r"^(.*?) -.*$", r"\1", title)
    # Remove non-ASCII characters
    title = re.sub(r"[^\x00-\x7F]+", "", title)
    # Remove after colon
    title = re.sub(r"^(.*?) :.*$", r"\1", title)
    # Strip leading and trailing whitespace
    title = title.strip()

    return title
